global:
  scrape_interval: 15s
  evaluation_interval: 30s


scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: url-shortner
    scrape_interval: 10s
    scrape_timeout: 5s
    body_size_limit: 10MB
    sample_limit: 1000
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [ "localhost:8080"]