name: Build and Test

on:
  push:
    branches:
      - [ "master" ] 
  pull_request:
    branches:
      - [ "master" ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: 1.17
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
